name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build C
        run: gcc -Wall -Wextra -std=c11 -o sistema-controle src/*.c
